### ISSUE TITLE
Incorrect property name for license key for Hazelcast 5.0

### ISSUE THREAD

**Issue by cheels** [hazelcast-guides/kubernetes-wan#3]
Current repository the **statefulset.yaml** files contains non compatible env name for the license. 

**Expected result:**
With Hazelcast 5.0 the name should be HZ_LICENSEKEY in both files: publisher/statefulset.yaml and receiver/statefulset.yaml

**Actual result:** 
The current value is HZ_LICENSE_KEY
```
....
          env:
          - name: HZ_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: hz-license-key
                key: license
....
```
With old key and new version (5.0-SNAPSHOT) the setup failed with error:
```
[5.0-SNAPSHOT] Node creation failed
hazelcast-0 hazelcast com.hazelcast.license.exception.InvalidLicenseException: License Key not configured!
```
